sample:
  4way:
    repeat: 1
    config:
      map_name: 4way_bordered
      robots_npcs: []
      robots_pcs: [ego0]
      robots_parked: []
      theta_tol_deg: 40
      dist_tol_m: 0.04
      min_dist: 0.5
      delta_y_m: 0.04
      only_straight: true


      nduckies: 0
      duckie_min_dist_from_other_duckie: 0.3
      duckie_min_dist_from_robot: 0.4
      duckie_y_bounds: [-0.1, -0.04]
      pc_robot_protocol: &pc_robot_protocol PROTOCOL_NORMAL
      npc_robot_protocol: &npc_robot_protocol  PROTOCOL_STATE
      tree_density: 0.8



  udem1:
    repeat: 1
    config:
      map_name: udem1_empty
      robots_npcs: []
      robots_pcs: [ego0]
      robots_parked: []
      theta_tol_deg: 40
      dist_tol_m: 0.04
      min_dist: 0.5
      delta_y_m: 0.04
      only_straight: true
      tree_density: 1.0

      nduckies: 0
      duckie_min_dist_from_other_duckie: 0.3
      duckie_min_dist_from_robot: 0.4
      duckie_y_bounds: [-0.1, -0.04]
      pc_robot_protocol: *pc_robot_protocol
      npc_robot_protocol: *npc_robot_protocol
