sample:
  loop:
    repeat: 1
    config:
      map_name: ETHZ_loop_bordered
      robots_npcs: [npc0,npc1,npc2]
      robots_pcs: [ego0]
      robots_parked: []
      theta_tol_deg: 40
      dist_tol_m: 0.04
      min_dist: 0.5
      delta_y_m: 0.04
      only_straight: true


      nduckies: 0
      duckie_min_dist_from_other_duckie: 0.3
      duckie_min_dist_from_robot: 0.4
      duckie_y_bounds: [-0.1, -0.04]
      pc_robot_protocol: &pc_robot_protocol  PROTOCOL_STATE
      npc_robot_protocol: &npc_robot_protocol PROTOCOL_STATE


  loop2:
    repeat: 1
    config:
      map_name: ETH_small_loop_2_bordered
      robots_npcs: [npc0]
      robots_pcs: [ego0]
      robots_parked: []
      theta_tol_deg: 40
      dist_tol_m: 0.04
      min_dist: 0.5
      delta_y_m: 0.04
      only_straight: true


      nduckies: 0
      duckie_min_dist_from_other_duckie: 0.3
      duckie_min_dist_from_robot: 0.4
      duckie_y_bounds: [-0.1, -0.04]
      pc_robot_protocol: *pc_robot_protocol
      npc_robot_protocol: *npc_robot_protocol


  autolab:
    repeat: 1
    config:
      map_name: ETHZ_autolab_technical_track_bordered
      robots_npcs: [npc0,npc1,npc2,npc3]
      robots_pcs: [ego0]
      robots_parked: []
      theta_tol_deg: 40
      dist_tol_m: 0.04
      min_dist: 0.5
      delta_y_m: 0.04
      only_straight: true



      nduckies: 0
      duckie_min_dist_from_other_duckie: 0.3
      duckie_min_dist_from_robot: 0.4
      duckie_y_bounds: [-0.1, -0.04]
      pc_robot_protocol: *pc_robot_protocol
      npc_robot_protocol: *npc_robot_protocol


  zigzag:
    repeat: 1
    config:
      map_name: zigzag_dists_bordered
      robots_npcs: []
      robots_pcs: [ego0]
      robots_parked: []
      theta_tol_deg: 40
      dist_tol_m: 0.04
      min_dist: 0.5
      delta_y_m: 0.04
      only_straight: false


      nduckies: 10
      duckie_min_dist_from_other_duckie: 0.3
      duckie_min_dist_from_robot: 0.4
      duckie_y_bounds: [-0.1, -0.04]
      pc_robot_protocol: *pc_robot_protocol
      npc_robot_protocol: *npc_robot_protocol
