map_name: udem1
robots_npcs: []
robots_pcs: [ego0,ego1,ego2,ego3]
robots_parked: []
theta_tol_deg: 40
dist_tol_m: 0.04
min_dist: 0.5
delta_y_m: 0.04
only_straight: true



nduckies: 0
duckie_min_dist_from_other_duckie: 0.3
duckie_min_dist_from_robot: 0.4
duckie_y_bounds: [-0.1, -0.04]
pc_robot_protocol: PROTOCOL_STATE
npc_robot_protocol: PROTOCOL_STATE
